const WRONG = 0;
const CORRECT = 1;
const POSITION_WRONG = 2;
const WORD_INPUT_SIZE = 50;
const WORDS = [
    "APPLE", "HOUSE", "WOMAN", "WHALE", "WATER", "TRUST", "SWEET", "STAKE", 
    "STAND", "SMILE", "SLATE", "SHINE", "ROUND", "RINSE", "REACT", "QUEST", 
    "PROUD", "PLUMB", "PLACE", "PEACH", "OCEAN", "NOISE", "MOUTH", "MANGO", 
    "LEMON", "LEAFY", "LARGE", "KNIFE", "JUDGE", "INDEX", "GRAPE"
];
export {WRONG, CORRECT, POSITION_WRONG, WORD_INPUT_SIZE, WORDS};